language: go
matrix:
  include:
    - go: 1.10.x
      script:
        - go vet ./
        - go test -race -v ./...
    - go: 1.11.x
      env: GO111MODULE=on
      script:
        - go vet ./
        - go test -race -v ./...
    - go: 1.11.x
      env: GO111MODULE=off
      script:
        - go vet ./
        - go test -race -v ./...
